apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: drawsguard-api-collector
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/wprojectl/api-collector-service:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 0
          timeoutSeconds: 240
          failureThreshold: 1
          periodSeconds: 240
kind: Service
metadata:
  name: drawsguard-api-collector
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/wprojectl/api-collector-service:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 0
          timeoutSeconds: 240
          failureThreshold: 1
          periodSeconds: 240
kind: Service
metadata:
  name: drawsguard-api-collector
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/wprojectl/api-collector-service:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 0
          timeoutSeconds: 240
          failureThreshold: 1
          periodSeconds: 240



